/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.google.gson.Gson;
import controller.MyThread;
import static controller.MyThread.dos;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.*;

/**
 *
 * @author Tattoo
 */
public class ChatRoomForm extends javax.swing.JFrame {

    /**
     * Creates new form ChatForm
     */
    public ByteArrayOutputStream fileData = new ByteArrayOutputStream();

    public ChatRoomForm() {
        initComponents();
        lbName.setText(MyThread.name);
//        showRoom();
    }

//    //Hiển thị list room
//    public void showRoom(){
//        for(Room i : MyThread.listRoom){
//            cbxRoom.addItem(i);
//        }
//    }
//    
//    //Hiển thị list user in room
//    public void showUIR(){
//        cbxUIR.removeAllItems();
//        for(UserInRoom i : MyThread.listUIR){
//            cbxUIR.addItem(i);
//        }
//    }
//    
//    //Hiển thị list page
//    public void showPage(Integer pageSize){
//        listPage.removeAll();
//        DefaultListModel m2 = new DefaultListModel();
//        for(Integer i = 1; i <= pageSize; i++){
//           m2.addElement(i);
//        }
//        listPage.setModel(m2);
//    }
//    
//    //Hiển thị khung lịch sử chat room
//     public void showMessage(List<Chat> listChat){
//        if(listChat == null){
//            return;
//        }
//        listFile.removeAll();
//        Collections.reverse(listChat);
//        DefaultListModel m1 = new DefaultListModel();
//        for(Chat i : listChat){
//            m1.addElement(i);
//        }
//        listFile.setModel(m1);
//    }
//    
//    //Thêm chat mới vào khung chat
//    public void addMessage(ChatMsg chatMsg, Long time){
//        SimpleDateFormat f = new SimpleDateFormat("dd-MM-yyyy hh:mm:ss");
//        String t= f.format(time);
//        Room r = (Room)cbxRoom.getSelectedItem();
//        //Khi đang chat với người gửi
//        if(Long.parseLong(chatMsg.getToRoomId()+"") == Long.parseLong(r.getId()+"")){
//            try{
//                //Gửi data lên cho server
//                Room selectRoom = (Room)cbxRoom.getSelectedItem();
//                UserInRoom fromUser = new UserInRoom();
//                fromUser.setUserId(MyThread.id);
//                ChatRoom chatRoom = new ChatRoom(fromUser, selectRoom.getId(), 1);
//                Gson gson = new Gson();
//                String dataJson = gson.toJson(chatRoom);
//                RawData rawData = new RawData("GET_ROOM_CHAT", MyThread.id, new Date().getTime(), dataJson);
//                String rawData1 = gson.toJson(rawData);
//                MyThread.dos.writeUTF(rawData1);
//                MyThread.dos.flush();
//                System.out.println(rawData1);
//            } catch(IOException e){
//                e.printStackTrace();
//            }
//        } else{
//            //Khi không chat với người gửi
//            txtNotify.append("(" + t + "): " + chatMsg.getFromUser().getNameUser() +
//                        " send new message to room\n");
//        }
//    }
//    
//    //Cập nhật phòng
//    public void addRoom(RoomAction roomAction){
//        Room room = new Room(roomAction.getRoomId(), roomAction.getNameRoom());
//        cbxRoom.addItem(room);
//    }
//    
//    //Cập nhật user vừa thêm
//    public void addUser(RoomAction roomAction){
//        cbxUIR.removeAllItems();
//        for(UserInRoom i : roomAction.getUserInRoomList()){
//            cbxUIR.addItem(i);
//        }
//    }
//    
//    //Cập nhật user vừa xoá
//    public void deleteUser(RoomAction roomAction){
//        List<UserInRoom> listUIR = roomAction.getUserInRoomList();
//        List<UserInRoom> listAll = MyThread.chatRoom.getListUserInRoom();
//        for(int i = 0; i < listUIR.size(); i++){
//            for(int j = 0; j < listAll.size(); j++){
//                if(listAll.get(j).getUserId() == listUIR.get(i).getUserId()){
//                    listAll.remove(listAll.get(j));
//                }
//            }
//        }
//        cbxUIR.removeAllItems();
//        for(UserInRoom i : listAll){
//            cbxUIR.addItem(i);
//        }
//    }
//    
//    //Cập nhật tiến độ tải file
//    public void updatePercent(Integer percent) throws InterruptedException{
//        percentBar.setValue((int)percent);
//        percentBar.setString(percent + "%");
//        Thread.sleep(20);
//    }
//    
//    //Đặt lại thanh progress
//    public void resetPercent(){
//        percentBar.setValue(0);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSend = new javax.swing.JButton();
        txtChat = new javax.swing.JTextField();
        cbxRoom = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNotify = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxUIR = new javax.swing.JComboBox();
        btBack = new javax.swing.JButton();
        btCreate = new javax.swing.JButton();
        btAddUser = new javax.swing.JButton();
        btDeleteUser = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPage = new javax.swing.JList<>();
        btSendFile = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listFile = new javax.swing.JList();
        btDownload = new javax.swing.JButton();
        percentBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btSend.setText("Send");
        btSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSendActionPerformed(evt);
            }
        });

        txtChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChatActionPerformed(evt);
            }
        });

        cbxRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRoomActionPerformed(evt);
            }
        });

        txtNotify.setColumns(20);
        txtNotify.setRows(5);
        jScrollPane3.setViewportView(txtNotify);

        jLabel1.setText("Notify");

        jLabel3.setText("Room");

        lbName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbName.setText("jLabel4");

        jLabel4.setText("User In Room");

        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        btCreate.setText("Create Room");
        btCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateActionPerformed(evt);
            }
        });

        btAddUser.setText("Add User");
        btAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddUserActionPerformed(evt);
            }
        });

        btDeleteUser.setText("Delete User");
        btDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteUserActionPerformed(evt);
            }
        });

        jLabel2.setText("Page:");

        listPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPageMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listPage);

        btSendFile.setText("Send File");
        btSendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSendFileActionPerformed(evt);
            }
        });

        listFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listFileMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(listFile);

        btDownload.setText("Download File");
        btDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDownloadActionPerformed(evt);
            }
        });

        percentBar.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(cbxRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbxUIR, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btCreate)
                                        .addGap(31, 31, 31)
                                        .addComponent(btAddUser)
                                        .addGap(43, 43, 43)
                                        .addComponent(btDeleteUser))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(jLabel1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbName)
                                .addGap(303, 303, 303))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(percentBar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtChat, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                                        .addComponent(jScrollPane4)))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btSend, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSendFile)
                        .addGap(40, 40, 40)
                        .addComponent(btDownload)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btSend)
                                    .addComponent(txtChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxUIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btCreate)
                                    .addComponent(btAddUser)
                                    .addComponent(btDeleteUser))
                                .addGap(52, 52, 52)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btDownload)
                            .addComponent(btSendFile)
                            .addComponent(percentBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btBack)
                        .addGap(23, 23, 23))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSendActionPerformed

    private void txtChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChatActionPerformed

    private void cbxRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRoomActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        // TODO add your handling code here:
        ChatForm.chatRoomForm.setVisible(false);
        MyThread.chat.setVisible(true);
    }//GEN-LAST:event_btBackActionPerformed

    private void btCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateActionPerformed
        // TODO add your handling code here:
        ChatForm.chatRoomForm.setVisible(false);
    }//GEN-LAST:event_btCreateActionPerformed

    private void btAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddUserActionPerformed
        // TODO add your handling code here:
        ChatForm.chatRoomForm.setVisible(false);
    }//GEN-LAST:event_btAddUserActionPerformed

    private void btDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteUserActionPerformed
        // TODO add your handling code here:
        ChatForm.chatRoomForm.setVisible(false);
    }//GEN-LAST:event_btDeleteUserActionPerformed

    private void listPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listPageMouseClicked

    private void btSendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSendFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSendFileActionPerformed

    private void btDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDownloadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDownloadActionPerformed

    private void listFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listFileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listFileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatRoomForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatRoomForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatRoomForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatRoomForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatRoomForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddUser;
    private javax.swing.JButton btBack;
    private javax.swing.JButton btCreate;
    private javax.swing.JButton btDeleteUser;
    private javax.swing.JButton btDownload;
    private javax.swing.JButton btSend;
    private javax.swing.JButton btSendFile;
    private javax.swing.JComboBox cbxRoom;
    private javax.swing.JComboBox cbxUIR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbName;
    private javax.swing.JList listFile;
    private javax.swing.JList<Integer> listPage;
    private javax.swing.JProgressBar percentBar;
    private javax.swing.JTextField txtChat;
    private javax.swing.JTextArea txtNotify;
    // End of variables declaration//GEN-END:variables
}
